### ISSUE TITLE
review

### ISSUE THREAD

**Issue by Ansurfen** [hiifong/TikTok#1]
https://github.com/hiifong/TikTok/blob/9c872fe942f9d9da784f21a753609f5233e25f81/modules/db/db.go#L10
为什么不弄一个GetDB的全局函数去暴露这个变量，直接引用全局变量虽然也行，但是不太优雅，如果你放到函数里面，到时候还能追踪调用栈之类的，做数据统计

https://github.com/hiifong/TikTok/blob/9c872fe942f9d9da784f21a753609f5233e25f81/modules/db/db.go#L12
这个Init为啥不用init让编译器自己初始化，这样写也挺不优雅的，其他地方也都是这个问题

https://github.com/hiifong/TikTok/blob/9c872fe942f9d9da784f21a753609f5233e25f81/modules/db/db.go#L16
这个初始化函数，就没必要大写了，既然都让Init做了

https://github.com/hiifong/TikTok/blob/9c872fe942f9d9da784f21a753609f5233e25f81/modules/config/config.go#L67
为啥不提供一个GetConf把*viper整个暴露出去，如果每个类型都要提供个GetXX 不是很啰嗦

https://github.com/hiifong/TikTok/blob/9c872fe942f9d9da784f21a753609f5233e25f81/routers/api/v1/api.go#L24
这个就很不符合常理，一般都是 /user , 包括他下面的都有这个问题

https://github.com/hiifong/TikTok/blob/9c872fe942f9d9da784f21a753609f5233e25f81/routers/init.go#L30
都用fmt.Sprint了，可以合成fmt.Sprintf

**Comment by hiifong** [comment]
> 这个Init为啥不用init让编译器自己初始化，这样写也挺不优雅的，其他地方也都是这个问题

关于初始化，我是想显示初始化。

> 这个就很不符合常理，一般都是 /user , 包括他下面的都有这个问题

这个是官方定义的接口。

非常感谢你的review。
